name: Full Deploy PrestaShop to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and Install PrestaShop
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.234.169.134 << EOF
          
            # Update and Install Dependencies
            sudo apt update && sudo apt upgrade -y
            sudo apt install apache2 mysql-server php php-mysql libapache2-mod-php php-cli php-curl php-zip php-gd php-mbstring php-xml php-bcmath php-json unzip -y
            
            # Download and Set Up PrestaShop
            wget https://github.com/PrestaShop/PrestaShop/releases/download/8.1.4/prestashop_8.1.4.zip
            unzip prestashop_8.1.4.zip -d prestashop
            sudo mv prestashop /var/www/html/prestashop
            sudo chown -R www-data:www-data /var/www/html/prestashop
            sudo chmod -R 755 /var/www/html/prestashop
            
            # Configure Apache Virtual Host
            sudo bash -c 'cat <<EOT > /etc/apache2/sites-available/prestashop.conf
            <VirtualHost *:80>
                ServerAdmin 13.234.169.134
                DocumentRoot /var/www/html/prestashop
                ServerName your-domain.com
                <Directory /var/www/html/prestashop/>
                    Options Indexes FollowSymLinks
                    AllowOverride All
                    Require all granted
                </Directory>
                ErrorLog \${APACHE_LOG_DIR}/error.log
                CustomLog \${APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            EOT'

            # Enable Site and Restart Apache
            sudo a2ensite prestashop.conf
            sudo a2enmod rewrite
            sudo systemctl daemon-reexec
            sudo systemctl reload apache2
            sudo systemctl restart apache2

            # Configure MySQL Database
            sudo mysql -u root <<MYSQL_SCRIPT
            CREATE DATABASE IF NOT EXISTS prestashop;
            CREATE USER IF NOT EXISTS 'ps_user'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
            GRANT ALL PRIVILEGES ON prestashop.* TO 'ps_user'@'localhost';
            FLUSH PRIVILEGES;
            MYSQL_SCRIPT

            echo "PrestaShop Deployment Complete"
          EOF
